import type { SprintGameDefinition } from './types'

export const firstImpressionSprint: SprintGameDefinition = {
  id: 'professional-presence-sprint',
  title: 'Professional Presence Sprint',
  trainingPathId: 'presence',
  completionThreshold: 75,
  scoreCategories: ['presence', 'communication', 'confidence', 'accountability'],
  scenes: [
    {
      id: 'lobby-arrival',
      title: 'Lobby Arrival',
      prompt: 'You walk into the office five minutes before a client prep meeting. What do you do first?',
      backgroundKey: 'lobby',
      correctChoiceId: 'arrive-ready',
      choices: [
        {
          id: 'check-phone',
          label: 'Check your phone while walking to the meeting room.',
          shortLabel: 'Check phone',
          supportingText: 'Walk in while reading notifications.',
          coaching: 'Phone-first arrival can make you look distracted before the work even starts.',
          animationKey: 'phone',
          soundKey: 'coach',
          categoryImpact: { presence: 5 },
        },
        {
          id: 'arrive-ready',
          label: 'Put your phone away, greet the front desk, and review your notes.',
          shortLabel: 'Arrive ready',
          supportingText: 'Greet the desk, put the phone away, and review notes.',
          coaching: 'Strong presence starts with preparation, awareness, and a respectful greeting.',
          animationKey: 'greeting',
          soundKey: 'positive',
          categoryImpact: { presence: 18, accountability: 8 },
        },
        {
          id: 'rush-in',
          label: 'Head straight in and hope you can catch up quickly.',
          shortLabel: 'Rush in',
          supportingText: 'Skip the reset moment and hope to catch up.',
          coaching: 'Speed helps, but unprepared arrival usually costs credibility.',
          animationKey: 'rush',
          soundKey: 'coach',
          categoryImpact: { accountability: 4 },
        },
      ],
    },
    {
      id: 'meeting-prep',
      title: 'Meeting Prep',
      prompt: 'The meeting starts soon. Which items belong in your quick prep stack?',
      backgroundKey: 'prep',
      correctChoiceId: 'agenda-questions',
      choices: [
        {
          id: 'agenda-questions',
          label: 'Agenda, two client questions, notebook, and the latest project update.',
          shortLabel: 'Prep stack',
          supportingText: 'Agenda, questions, notebook, and project update.',
          coaching: 'Prepared employees make it easier for the whole room to move with confidence.',
          animationKey: 'prep-stack',
          soundKey: 'positive',
          categoryImpact: { presence: 10, accountability: 14 },
        },
        {
          id: 'empty-notebook',
          label: 'Notebook only. You can improvise once people start talking.',
          shortLabel: 'Notebook only',
          supportingText: 'Bring a notebook and plan to improvise.',
          coaching: 'Improvising can work in small moments, but it should not replace preparation.',
          animationKey: 'notebook',
          soundKey: 'coach',
          categoryImpact: { confidence: 5 },
        },
        {
          id: 'everything',
          label: 'Bring every file you can find so nothing is missing.',
          shortLabel: 'Bring everything',
          supportingText: 'Carry every file, even the unrelated ones.',
          coaching: 'Too much clutter slows decisions. Prepared means relevant, not overloaded.',
          animationKey: 'clutter',
          soundKey: 'coach',
          categoryImpact: { accountability: 6 },
        },
      ],
    },
    {
      id: 'client-meeting',
      title: 'Client Meeting',
      prompt: 'A client asks for an update on a delayed task. What answer sounds most professional?',
      backgroundKey: 'meeting',
      correctChoiceId: 'clear-recovery-plan',
      choices: [
        {
          id: 'vague-update',
          label: 'We are still working on it. I should know more later.',
          shortLabel: 'Stay vague',
          supportingText: 'Give a broad update without a clear next step.',
          coaching: 'Vague updates create uncertainty and invite more follow-up.',
          animationKey: 'vague',
          soundKey: 'coach',
          categoryImpact: { communication: 6 },
        },
        {
          id: 'clear-recovery-plan',
          label: 'We are one day behind. Here are the blockers and the recovery plan.',
          shortLabel: 'Recovery plan',
          supportingText: 'Name the delay, blockers, and next action.',
          coaching: 'Clear, accountable updates build trust even when the news is imperfect.',
          animationKey: 'recovery-plan',
          soundKey: 'positive',
          categoryImpact: { communication: 16, accountability: 12, confidence: 6 },
        },
        {
          id: 'blame-system',
          label: 'The system caused the delay, so there was not much we could do.',
          shortLabel: 'Blame system',
          supportingText: 'Point to the problem without owning a next step.',
          coaching: 'Blame lowers confidence in your ownership. Name the issue and the next action.',
          animationKey: 'blame',
          soundKey: 'coach',
          categoryImpact: { communication: 3 },
        },
      ],
    },
    {
      id: 'feedback-moment',
      title: 'Feedback Moment',
      prompt: 'Your manager gives direct feedback after the meeting. How do you respond?',
      backgroundKey: 'feedback',
      correctChoiceId: 'clarify-commit',
      choices: [
        {
          id: 'defend',
          label: 'Explain why the situation was harder than it looked.',
          shortLabel: 'Defend',
          supportingText: 'Lead with why the feedback does not fit.',
          coaching: 'Context matters, but defensiveness can hide the lesson.',
          animationKey: 'defend',
          soundKey: 'coach',
          categoryImpact: { confidence: 4 },
        },
        {
          id: 'clarify-commit',
          label: 'Ask one clarifying question and commit to the next improvement.',
          shortLabel: 'Clarify and commit',
          supportingText: 'Ask one question and name the next improvement.',
          coaching: 'Composed follow-up shows confidence, humility, and ownership.',
          animationKey: 'clarify',
          soundKey: 'positive',
          categoryImpact: { confidence: 16, communication: 8, accountability: 8 },
        },
        {
          id: 'quiet',
          label: 'Nod quietly and avoid the topic for the rest of the day.',
          shortLabel: 'Go quiet',
          supportingText: 'Nod without asking what to improve.',
          coaching: 'Silence can look like agreement, but it misses a chance to grow.',
          animationKey: 'quiet',
          soundKey: 'coach',
          categoryImpact: { presence: 3 },
        },
      ],
    },
    {
      id: 'goal-ladder',
      title: 'Goal Ladder',
      prompt: 'Before the day ends, choose a goal that turns training into action.',
      backgroundKey: 'goals',
      correctChoiceId: 'specific-goal',
      choices: [
        {
          id: 'general-goal',
          label: 'Be more professional next week.',
          shortLabel: 'Broad goal',
          supportingText: 'Choose a good idea that is hard to measure.',
          coaching: 'Good intent, but the goal is too broad to measure.',
          animationKey: 'broad-goal',
          soundKey: 'coach',
          categoryImpact: { confidence: 4 },
        },
        {
          id: 'specific-goal',
          label: 'Prepare two questions before each client meeting this week.',
          shortLabel: 'Specific goal',
          supportingText: 'Pick a clear action you can practice this week.',
          coaching: 'Specific goals are easier to practice, track, and prove.',
          animationKey: 'specific-goal',
          soundKey: 'positive',
          categoryImpact: { accountability: 14, confidence: 8, presence: 6 },
        },
        {
          id: 'huge-goal',
          label: 'Never make a communication mistake again.',
          shortLabel: 'Perfect forever',
          supportingText: 'Set an impossible goal that cannot be tracked.',
          coaching: 'Growth goals should stretch you without setting an impossible standard.',
          animationKey: 'impossible-goal',
          soundKey: 'coach',
          categoryImpact: { accountability: 4 },
        },
      ],
    },
  ],
}
