import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * Dynamic Expo config.
 *
 * The static baseline lives in `app.json`; this file layers environment-driven
 * values on top so the same binary can point at different backends without a
 * source edit. Everything here is build-time metadata only — NO secrets. The
 * Amplify/Cognito wiring is delivered at runtime by `amplify_outputs.json`
 * (generated by `npx ampx sandbox` / a deployed backend), never hardcoded here.
 *
 * This is a CUSTOM DEV CLIENT app (expo-dev-client): it uses native modules
 * (react-native-video, WatermelonDB, NetInfo, Amplify) that are NOT in Expo Go,
 * so it must be run via a dev client build (`expo run:ios` / `expo run:android`
 * or an EAS dev build), not Expo Go.
 */
export default ({ config }: ConfigContext): ExpoConfig => {
  const appEnv = process.env.APP_ENV ?? 'development';

  return {
    ...config,
    name: config.name ?? 'Soteria Forge',
    slug: config.slug ?? 'soteria-forge-mobile',
    extra: {
      ...config.extra,
      appEnv,
      // Non-secret runtime hints. Real Cognito/AppSync config is loaded from
      // amplify_outputs.json at runtime (see src/auth/amplifyConfig.ts).
      xapiSyncBatchSize: Number(process.env.XAPI_SYNC_BATCH_SIZE ?? 25),
    },
  };
};
